config/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from config.views import favicon_file

urlpatterns = [
    path("apple-touch-icon.png", favicon_file),
    path("favicon.ico", favicon_file),
    path("favicon-96x96.png", favicon_file),
    path("favicon.svg", favicon_file),
    path("web-app-manifest-192x192.png", favicon_file),
    path("web-app-manifest-512x512.png", favicon_file),
    path("site.webmanifest", favicon_file),
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
]

core/urls.py
from django.urls import path

from core.views import home
from core.views import mark_viewed
from core.views import project_archive_view
from core.views import stats_view

app_name = "core"
urlpatterns = [
    path("", home, name="home"),
    path("projects/<int:pk>/mark-as-viewed/", mark_viewed, name="mark-viewed"),
    path("projects/archive/", project_archive_view, name="projects-archive"),
    path("stats/", stats_view, name="stats"),
]

core/models.py
from urllib.parse import urlparse

from django.db import models


class TimestampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class BaseModel(TimestampModel):
    class Meta:
        abstract = True


class Project(BaseModel):
    title = models.CharField(max_length=255)
    url = models.URLField(unique=True, max_length=1000)
    description = models.TextField(default="")
    viewed = models.DateTimeField(null=True)
    published_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-viewed"]

    def __str__(self):
        return self.title

    @property
    def source(self):
        return urlparse(self.url).netloc

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

config/views.py
from django.conf import settings
from django.http import FileResponse
from django.views.decorators.cache import cache_control
from django.views.decorators.http import require_GET


@require_GET
@cache_control(max_age=60 * 60 * 24, immutable=True, public=True)
def favicon_file(request):
    name = "favicon-dev.png" if settings.DEBUG else request.path.lstrip("/")
    file = (settings.BASE_DIR / "static" / "img" / name).open("rb")
    return FileResponse(file)

core/views.py
from datetime import timedelta

from django.core.paginator import EmptyPage
from django.core.paginator import Paginator
from django.db.models import Count
from django.db.models import F
from django.db.models import TextChoices
from django.db.models import Value
from django.db.models.functions import StrIndex
from django.db.models.functions import Substr
from django.db.models.functions import TruncDate
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from django.views.generic import TemplateView

from core.models import Project
from core.scrapers import SOURCES_CONFIG
from core.services import get_new_projects


def home(request):
    get_new_projects()
    new_projects = Project.objects.filter(viewed__isnull=True).order_by(F("published_at").desc(nulls_last=True))
    new_projects_stats = {
        "emploitic.com": new_projects.filter(url__icontains="https://emploitic.com/").count(),
        "nafezly.com": new_projects.filter(url__icontains="https://nafezly.com/").count(),
        "ouedkniss.com": new_projects.filter(url__icontains="https://ouedkniss.com/").count(),
        "baaeed.com": new_projects.filter(url__icontains="https://baaeed.com/").count(),
        "bahr.sa": new_projects.filter(url__icontains="https://bahr.sa/").count(),
        "mostaql.com": new_projects.filter(url__startswith="https://mostaql.com").count(),
    }
    return render(
        request,
        "core/home.html",
        {
            "projects": new_projects,
            "new_projects_stats": new_projects_stats,
        },
    )


class PeriodOption(TextChoices):
    LAST_7_DAYS = "7", "Last 7 days"
    LAST_30_DAYS = "30", "Last 30 days"
    LAST_3_MONTHS = "90", "Last 3 months"


class StatsView(TemplateView):
    SOURCES = sorted(SOURCES_CONFIG.keys())
    SOURCE_COLORS = [SOURCES_CONFIG[source]["color"] for source in SOURCES]

    def get_template_names(self):
        if self.request.htmx:
            return ["core/stats.html#daily-projects-card"]
        return ["core/stats.html"]

    def get_projects_by_source(self):
        return Project.objects.annotate(
            protocol_pos=StrIndex("url", Value("://")),
            after_protocol=Substr("url", 3 + F("protocol_pos")),
            slash_pos=StrIndex(F("after_protocol"), Value("/")),
            source=Substr(F("after_protocol"), 1, F("slash_pos") - 1),
        )

    def get_daily_stats(self, day_list):
        daily_stats = (
            self.get_projects_by_source()
            .filter(published_at__gte=day_list[0])
            .annotate(day=TruncDate("published_at"))
            .values("day", "source")
            .annotate(count=Count("id"))
        )
        return self._format_daily_counts(daily_stats, day_list)

    def _format_daily_counts(self, daily_stats, day_list):
        source_daily_count = []
        for source in self.SOURCES:
            counts = [
                next((item["count"] for item in daily_stats if item["source"] == source and item["day"] == day), 0)
                for day in day_list
            ]
            source_daily_count.append({"name": source, "data": counts})
        return source_daily_count

    def _calculate_source_totals(self, daily_stats):
        source_totals = {}
        for source_count in daily_stats:
            source = source_count["name"]
            source_totals[source] = sum(source_count["data"])
        return source_totals

    def get_day_list(self):
        period = self.request.GET.get("period")
        period = period if period in PeriodOption.values else PeriodOption.LAST_7_DAYS.value
        start_date = timezone.now().date() - timedelta(days=1)
        day_list = [start_date - timedelta(days=i) for i in range(int(period))]
        day_list.reverse()
        return day_list

    def get(self, request, *args, **kwargs):
        projects_by_source = (
            self.get_projects_by_source().values("source").annotate(total=Count("id")).order_by("source")
        )
        day_list = self.get_day_list()
        source_daily_count = self.get_daily_stats(day_list)
        source_total = self._calculate_source_totals(source_daily_count)
        context = {
            "source_daily_count": source_daily_count,
            "source_totals": source_total,
            "daily_total": sum(source_total.values()),
            "source_colors": self.SOURCE_COLORS,
            "day_list": day_list,
            "projects_per_source": list(projects_by_source),
            "project_count": Project.objects.count(),
            "PeriodOption": PeriodOption,
            "selected_period_label": dict(PeriodOption.choices).get(
                self.request.GET.get("period"),
                PeriodOption.LAST_7_DAYS.label,
            ),
        }
        return self.render_to_response(context)


stats_view = StatsView.as_view()


def project_archive_view(request):
    qs = Project.objects.filter(viewed__isnull=False)
    template = "core/projects-archive.html"
    paginator = Paginator(qs, 25)
    page_number = request.GET.get("page") or 1
    try:
        page = paginator.page(int(page_number))
    except (ValueError, EmptyPage):
        page = paginator.page(1)

    if request.htmx:
        template = "core/projects-archive.html#project-list"

    return render(
        request,
        template,
        {
            "page": page,
        },
    )


@require_http_methods(["PUT"])
def mark_viewed(request, pk):
    project = get_object_or_404(Project, pk=pk)
    project.viewed = timezone.now()
    project.save()
    return HttpResponse(status=204)

users/views.py
# Create your views here.

templates/base.html
<!--
* Tabler - Premium and Open Source dashboard template with responsive and high quality UI.
* @version 1.0.0-beta20
* @link https://tabler.io
* Copyright 2018-2023 The Tabler Authors
* Copyright 2018-2023 codecalm.net Paweł Kuna
* Licensed under MIT (https://github.com/tabler/tabler/blob/master/LICENSE)
-->
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
    <meta name="apple-mobile-web-app-title" content="WorkPulse" />
    <link rel="manifest" href="/site.webmanifest" />
    <title>
      {% block title %}
        WorkPulse
      {% endblock title %}
    </title>
    <!-- CSS files -->
    <link href="{% static 'css/tabler.css' %}" rel="stylesheet" />
    <link href="{% static 'css/app.css' %}" rel="stylesheet" />
    <style>
      @import url('https://rsms.me/inter/inter.css');

      :root {
        /*--tblr-font-sans-serif: 'Inter Var', -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;*/
        --tblr-font-sans-serif: "Fira Sans", "Noto Sans Arabic";
      }

      body {
        font-feature-settings: "cv03", "cv04", "cv11";
      }
    </style>
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <script src="{% static 'js/demo-theme.js' %}"></script>
    <div class="page">
      <!-- Navbar -->
      {% include "includes/navbar.html" %}
      <div class="page-wrapper">
        <!-- Page header -->
        <div class="page-header d-print-none">
          <div class="container-xl">
            <div class="row g-2 align-items-center">
              <div class="col">
                <!-- Page pre-title -->
                <div class="page-pretitle">
                  {% block page_pretitle %}
                  {% endblock page_pretitle %}
                </div>
                <h2 class="page-title">
                  {% block page_title %}
                  {% endblock page_title %}
                </h2>
              </div>
              <!-- Page title actions -->
              <div class="col-auto ms-auto d-print-none">
                <div class="btn-list">
                  {% block page_title_actions %}
                  {% endblock page_title_actions %}
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Page body -->
        <div class="page-body">
          <div class="container-xl">
            {% block content %}
            {% endblock content %}
          </div>
        </div>
        {% include "includes/footer.html" %}
      </div>
    </div>
    <script src="{% static 'js/tabler.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.3/dist/htmx.min.js"
            integrity="sha256-SRlVzRgQdH19e5zLk2QAr7dg4G0l1T5FcrZLZWOyeE4="
            crossorigin="anonymous"
            defer></script>
    <script src="https://cdn.jsdelivr.net/npm/hyperscript.org@0.9.13/dist/hdb.min.js"
            integrity="sha256-eqsD5t9zqxRfgY93GIt7yy5ckoxF/aiU5MRHMiAFnq4="
            crossorigin="anonymous"
            defer></script>
    <script src="{% static 'js/apexcharts.min.js' %}" defer></script>
    <script src="{% static 'js/app.js' %}" defer></script>
    {% block inline_javascript %}
    {% endblock inline_javascript %}
  </body>
</html>

templates/core/home.html
{% extends 'base.html' %}

{% load static %}
{% load core_extra %}

{% block title %}
  Home | {{ block.super }}
{% endblock title %}
{% block page_title %}
  New Projects
{% endblock page_title %}
{% block content %}
  <div class="row mb-3">
    <div class="col-md-4 mb-3">
      <div class="row g-3 sticky-md-top">
        {% for source, count in new_projects_stats.items %}
          <div class="col-6">
            <div class="card p-2 shadow-sm">
              <div class="row align-items-center">
                <div class="col-auto">
                  <div class="text-muted mb-2">{{ source }}</div>
                  <div class="fs-3 fw-bold">{{ count }}</div>
                </div>
                <div class="col text-end">
                  <img src="{% static 'img/'|add:source|add:'.png' %}"
                       width="45"
                       alt="{{ source }} logo" />
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        <div class="col-12">
          <div class="card p-2 shadow-sm">
            <div class="row align-items-center">
              <div class="col-auto">
                <div class="text-muted mb-2">Total</div>
                <div class="fs-3 fw-bold">{{ projects.count }}</div>
              </div>
              <div class="col text-end">
                <img src="{% static 'img/sum.svg' %}" width="45" alt="sum logo" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      {% for project in projects %}
        <div class="card project-card">
          <div class="card-body">
            <div class="d-flex">
              <img src="{% static 'img/'|add:project.source|add:'.png' %}"
                   class="rounded-circle me-3 avatar"
                   alt="{{ project.source }} logo" />
              <div class="flex-grow-1">
                <div class="mb-1">
                  <span class="fw-bold">{{ project.source }}</span>
                  {% if project.published_at %}
                    <span class="text-muted"
                          title="{{ project.published_at|date:'H:i' }} · {{ project.published_at|date:'d-m-Y' }}">
                      {{ project.published_at|short_since }}
                    </span>
                  {% endif %}
                  <span class="viewed text-primary d-none">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         width="24"
                         height="24"
                         viewBox="0 0 24 24"
                         fill="none"
                         stroke="currentColor"
                         stroke-width="2"
                         stroke-linecap="round"
                         stroke-linejoin="round"
                         class="icon icon-tabler icons-tabler-outline icon-tabler-eye-check">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                      <path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" />
                      <path d="M11.102 17.957c-3.204 -.307 -5.904 -2.294 -8.102 -5.957c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6a19.5 19.5 0 0 1 -.663 1.032" />
                      <path d="M15 19l2 2l4 -4" />
                    </svg>
                  </span>
                </div>
                <div class="card-text mb-2 fs-3">
                  <h3 dir="auto">
                    <a href="{{ project.url }}" class="position-relative" target="_blank">{{ project.title }}</a>
                  </h3>
                  <div class="position-relative">
                    <div class="text-clip"
                         dir="auto"
                         hx-put="{% url 'core:mark-viewed' project.pk %}"
                         hx-trigger="intersect threshold:1 once"
                         hx-on::after-request="if(event.detail.successful)this.closest('.project-card').querySelector('.viewed').classList.remove('d-none')">
                      {% if project.source == 'emploitic.com' %}
                        {{ project.description|safe }}
                      {% else %}
                        {{ project.description|linebreaks }}
                      {% endif %}
                    </div>
                    <a class="expand-btn stretched-link">Show more</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/core/projects-archive.html
{% extends 'base.html' %}

{% load partials %}

{% block title %}
  Projects Archive | {{ block.super }}
{% endblock title %}
{% block content %}
  <h1>Projects Archive</h1>
  {% partialdef project-list inline %}
  {% for project in page.object_list %}
    <div class="card mb-2"
         dir="rtl"
         {% if forloop.last and page.has_next %} hx-get="./?page={{ page.next_page_number }}" hx-trigger="revealed" hx-swap="afterend" {% endif %}>
      <div class="card-body">
        <div class="row mb-3">
          <div class="col-12 fs-3 fw-bold">
            <a href="{{ project.url }}" target="_blank">{{ project.title }}</a>
          </div>
        </div>
        <div class="row">
          <div class="col-5 col-md-3">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24"
                 viewBox="0 0 24 24"
                 fill="none"
                 stroke="currentColor"
                 stroke-width="2"
                 stroke-linecap="round"
                 stroke-linejoin="round"
                 class="icon icon-tabler icons-tabler-outline icon-tabler-world">
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0" />
              <path d="M3.6 9h16.8" />
              <path d="M3.6 15h16.8" />
              <path d="M11.5 3a17 17 0 0 0 0 18" />
              <path d="M12.5 3a17 17 0 0 1 0 18" />
            </svg>
            <span class="text-muted fw-bold">{{ project.source }}</span>
          </div>
          <div class="col-7 col-md-3">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24"
                 viewBox="0 0 24 24"
                 fill="none"
                 stroke="currentColor"
                 stroke-width="2"
                 stroke-linecap="round"
                 stroke-linejoin="round"
                 class="icon icon-tabler icons-tabler-outline icon-tabler-eye-check">
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" />
              <path d="M11.102 17.957c-3.204 -.307 -5.904 -2.294 -8.102 -5.957c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6a19.5 19.5 0 0 1 -.663 1.032" />
              <path d="M15 19l2 2l4 -4" />
            </svg>
            <span class="text-muted fw-bold">{{ project.viewed|date:"Y-m-d H:i:s" }}</span>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endpartialdef project-list %}
{% endblock content %}

templates/includes/footer.html
<footer class="footer footer-transparent d-print-none">
  <div class="container-xl">
    <div class="row text-center align-items-center flex-row-reverse">
      <div class="col-lg-auto ms-lg-auto">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">
            <a href="https://github.com/oussama-he/"
               target="_blank"
               class="link-secondary"
               rel="noopener">
              <svg xmlns="http://www.w3.org/2000/svg"
                   width="24"
                   height="24"
                   viewBox="0 0 24 24"
                   fill="none"
                   stroke="currentColor"
                   stroke-width="2"
                   stroke-linecap="round"
                   stroke-linejoin="round"
                   class="icon icon-tabler icons-tabler-outline icon-tabler-brand-github">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5" />
              </svg>
            </a>
            <a href="https://linkedin.com/in/oussama-he/"
               target="_blank"
               class="link-secondary"
               rel="noopener">
              <svg xmlns="http://www.w3.org/2000/svg"
                   width="24"
                   height="24"
                   viewBox="0 0 24 24"
                   fill="none"
                   stroke="currentColor"
                   stroke-width="2"
                   stroke-linecap="round"
                   stroke-linejoin="round"
                   class="icon icon-tabler icons-tabler-outline icon-tabler-brand-linkedin">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M8 11v5" />
                <path d="M8 8v.01" />
                <path d="M12 16v-5" />
                <path d="M16 16v-3a2 2 0 1 0 -4 0" />
                <path d="M3 7a4 4 0 0 1 4 -4h10a4 4 0 0 1 4 4v10a4 4 0 0 1 -4 4h-10a4 4 0 0 1 -4 -4z" />
              </svg>
            </a>
            <span>/oussama-he</span>
          </li>
        </ul>
      </div>
      <div class="col-12 col-lg-auto mt-3 mt-lg-0">Built using Tabler Admin Dashboard.</div>
    </div>
  </div>
</footer>

templates/includes/navbar.html
{% load static %}

<header class="navbar navbar-expand-md d-print-none">
  <div class="container-xl">
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar-menu"
            aria-controls="navbar-menu"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
      <a href=".">
        <img src="{% static 'img/logo.png' %}"
             width="110"
             height="40"
             alt="WorkPulse"
             class="navbar-brand-image" />
      </a>
    </h1>
    <div class="navbar-nav flex-row order-md-last">
      <div class="nav-item d-none d-md-flex me-3">
        <div class="btn-list"></div>
      </div>
      <div class="d-none d-md-flex">
        <a href="?theme=dark"
           class="nav-link px-0 hide-theme-dark"
           title="Enable dark mode"
           data-bs-toggle="tooltip"
           data-bs-placement="bottom">
          <!-- Download SVG icon from http://tabler-icons.io/i/moon -->
          <svg xmlns="http://www.w3.org/2000/svg"
               class="icon"
               width="24"
               height="24"
               viewBox="0 0 24 24"
               stroke-width="2"
               stroke="currentColor"
               fill="none"
               stroke-linecap="round"
               stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z" />
          </svg>
        </a>
        <a href="?theme=light"
           class="nav-link px-0 hide-theme-light"
           title="Enable light mode"
           data-bs-toggle="tooltip"
           data-bs-placement="bottom">
          <!-- Download SVG icon from http://tabler-icons.io/i/sun -->
          <svg xmlns="http://www.w3.org/2000/svg"
               class="icon"
               width="24"
               height="24"
               viewBox="0 0 24 24"
               stroke-width="2"
               stroke="currentColor"
               fill="none"
               stroke-linecap="round"
               stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path d="M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0" />
            <path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7" />
          </svg>
        </a>
      </div>
    </div>
  </div>
</header>
<header class="navbar-expand-md">
  <div class="collapse navbar-collapse" id="navbar-menu">
    <div class="navbar">
      <div class="container-xl">
        <ul class="navbar-nav">
          {% url 'core:home' as home_url %}
          <li class="nav-item {% if request.path == home_url %}active{% endif %}">
            <a class="nav-link" href="{{ home_url }}">
              <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                <svg xmlns="http://www.w3.org/2000/svg"
                     class="icon"
                     width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     stroke-width="2"
                     stroke="currentColor"
                     fill="none"
                     stroke-linecap="round"
                     stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                  <path d="M5 12l-2 0l9 -9l9 9l-2 0" />
                  <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" />
                  <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" />
                </svg>
              </span>
              <span class="nav-link-title">Home</span>
            </a>
          </li>
          {% url 'core:stats' as stats_url %}
          <li class="nav-item {% if request.path == stats_url %}active{% endif %}">
            <a class="nav-link" href="{{ stats_url }}">
              <span class="nav-link-icon d-md-none d-lg-inline-block">
                <svg xmlns="http://www.w3.org/2000/svg"
                     width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     fill="none"
                     stroke="currentColor"
                     stroke-width="2"
                     stroke-linecap="round"
                     stroke-linejoin="round"
                     class="icon icon-tabler icons-tabler-outline icon-tabler-chart-histogram">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                  <path d="M3 3v18h18" />
                  <path d="M20 18v3" />
                  <path d="M16 16v5" />
                  <path d="M12 13v8" />
                  <path d="M8 16v5" />
                  <path d="M3 11c6 0 5 -5 9 -5s3 5 9 5" />
                </svg>
              </span>
              <span class="nav-link-title">Stats</span>
            </a>
          </li>
          {% url 'core:projects-archive' as projects_archive_url %}
          <li class="nav-item {% if request.path == projects_archive_url %}active{% endif %}">
            <a class="nav-link" href="{{ projects_archive_url }}">
              <span class="nav-link-icon d-md-none d-lg-inline-block">
                <svg xmlns="http://www.w3.org/2000/svg"
                     width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     fill="none"
                     stroke="currentColor"
                     stroke-width="2"
                     stroke-linecap="round"
                     stroke-linejoin="round"
                     class="icon icon-tabler icons-tabler-outline icon-tabler-archive">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                  <path d="M3 4m0 2a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v0a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2z" />
                  <path d="M5 8v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-10" />
                  <path d="M10 12l4 0" />
                </svg>
              </span>
              <span class="nav-link-title">Archive</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>